const $=(s,c=document)=>c.querySelector(s);const $$=(s,c=document)=>[...c.querySelectorAll(s)];
const body=document.body,overlay=$('.overlay'),cart=$('.cart-drawer'),mobile=$('.mobile-nav'),search=$('.search-panel');let cartItems=[];
function togglePanel(panel,open){panel.classList.toggle('open',open);panel.setAttribute('aria-hidden',String(!open));overlay.classList.toggle('open',open);body.style.overflow=open?'hidden':''}
$('.cart-btn').addEventListener('click',()=>togglePanel(cart,true));$('.cart-close').addEventListener('click',()=>togglePanel(cart,false));
$('.menu-btn').addEventListener('click',()=>togglePanel(mobile,true));$('.mobile-close').addEventListener('click',()=>togglePanel(mobile,false));
$('.search-btn').addEventListener('click',()=>{togglePanel(search,true);setTimeout(()=>$('.search-panel input').focus(),250)});$('.search-close').addEventListener('click',()=>togglePanel(search,false));
overlay.addEventListener('click',()=>{[cart,mobile,search].forEach(p=>togglePanel(p,false))});$$('.mobile-nav a').forEach(a=>a.addEventListener('click',()=>togglePanel(mobile,false)));
$$('.wish').forEach(b=>b.addEventListener('click',()=>{b.classList.toggle('active');b.textContent=b.classList.contains('active')?'♥':'♡'}));
$$('.quick-add').forEach(btn=>btn.addEventListener('click',()=>{const card=btn.closest('.product-card'),name=$('h3',card).textContent,price=$('strong',card).textContent.trim().split(' ').pop(),image=$('img',card).src;cartItems.push({name,price,image});renderCart();const t=$('.toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}));
function renderCart(){const count=$('.cart-count');count.textContent=cartItems.length;$('.cart-btn').setAttribute('aria-label',`Cart with ${cartItems.length} items`);const wrap=$('.cart-items');wrap.innerHTML=cartItems.length?cartItems.map(i=>`<div class="cart-line"><img src="${i.image}" alt=""><div><h4>${i.name}</h4><p>${i.price}</p></div></div>`).join(''):'<p class="empty-cart">Your bag is waiting.</p>';const total=cartItems.reduce((n,i)=>n+Number(i.price.replace(/[^0-9.]/g,'')),0);$('.subtotal').textContent=`$${total.toFixed(0)}`}
$$('.tabs button').forEach(btn=>btn.addEventListener('click',()=>{$$('.tabs button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const cat=btn.textContent.toLowerCase();$$('.product-card').forEach(card=>card.style.display=cat==='all pieces'||card.dataset.category===cat?'block':'none')}));
$('.newsletter').addEventListener('submit',e=>{e.preventDefault();$('.form-message').textContent='Thank you — your first note is on its way.';e.target.reset()});
$('.search-form').addEventListener('submit',e=>{e.preventDefault();const q=$('.search-panel input').value.toLowerCase();togglePanel(search,false);document.querySelector('#shop').scrollIntoView();$$('.product-card').forEach(c=>c.style.display=c.innerText.toLowerCase().includes(q)||!q?'block':'none')});
